language: scala

sudo: false

matrix:
  include:
  - env: SBT_VERSION="1.1.4" COMMAND="clean test scalafmtCheck"
    jdk: oraclejdk8
    scala: 2.11.12
  - env: SBT_VERSION="1.1.4" COMMAND="clean test scalafmtCheck"
    jdk: oraclejdk8
    scala: 2.12.6
  - env: SBT_VERSION="1.1.4" COMMAND="clean test scalafmtCheck docs/makeSite"
    jdk: oraclejdk9
    scala: 2.12.6

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "^^${SBT_VERSION}" $COMMAND

before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_1444cb71e00b_key -iv $encrypted_1444cb71e00b_iv -in project/secrets.tar.enc -out local.secrets.tar -d;
      tar -xf local.secrets.tar -C project;
    fi

before_deploy:
  # Record minimal build information via the Git user ident
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  # Decrypt the secret deploy key using instructions from `travis encrypt-file
  - openssl aes-256-cbc -K $encrypted_8b0aa0b7878c_key -iv $encrypted_8b0aa0b7878c_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
  - chmod 600 project/travis-deploy-key
  # Start ssh-agent in the background and load the deploy key
  - eval "$(ssh-agent -s)"
  - ssh-add project/travis-deploy-key
  - chmod a+x project/deploy.sh

deploy:
  - provider: script
    script: ./project/deploy.sh
    skip_cleanup: true
    on:
      jdk: oraclejdk9
      scala: 2.12.6
      branch: master
  - provider: script
    script: ./project/deploy.sh
    skip_cleanup: true
    on:
      jdk: oraclejdk9
      scala: 2.12.6
      tags: true

notifications:
  email:
    on_success: never
    on_failure: always
  irc: irc.freenode.org#cilib
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9df9c83ef091cee2f675
    on_success: always
    on_failure: always

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

git:
  depth: 200

env:
  global:
  - secure: "F5930bzECZ3rm062ng6hn8U0B3PL0d+Vqnow+J9aOwu7bK/ecqZUSpud+04GryCsuPDnAL8F5RqF74sa7ib3NAU4IqiozcyITfr7R+NXVKVU/OhLANRnNnGXQaSL6/4gd2NvtONeLiSvmfTJtQtYezBukmhAFkU2a27Pp8CwCas="
  - secure: "PoAdWHYX5wkBtcczX69mF2N8lNevm5G2ThBYJOtgvVovXTPl6QK9FhXxOTl8qRwpW9DdT0tWZkbgfYz6ZKY8wW3s/HCYr876VKA+qkh0LraOUv4gtL3td2Rhz/iKchaRiQfht8kN04F7T9h29xuwrXeRDQ/C3j2oIMo+VhnBfdw="
  - secure: "CGDqHPcQr/dsJgd9yMn+quPu84ndSACYC3yedU5cIeuxrxRX2Ut6VkfUuqPco1Qsqd7XZwulfvw//KSAy7E+I6mhlH5LW/b0IqRqOb0SgpFM9zsGMBLOts8wGWjgUWF1Vn+Tlg16OrwHUzXpLvS+a6i6linL7+rPRmjuGkwyx7M="
